### ISSUE TITLE
The folder does not exist

### ISSUE THREAD

**Issue by TimetravelerDD** [OmegaRogue/FusionStyle#2]
I don't have an Autodesk folder in C:\Program Files

Where should i put those files?

**Comment by OmegaRogue** [comment]
I don't really use fusion anymore these days, so i dont know what has changed, but if the location changed, then you need to find the new webdeploy folder, easiest is probably to just search for webdeploy in C:\

**Comment by TimetravelerDD** [comment]
great idea, thanks. for me it was in 

C:\Users\work\AppData\Local\Autodesk\webdeploy\production\22e664d43fce268ac9bf1fa1cda69e4a9585c997

this tells me Fusion got installed on a user basis – I don't remember if I had an option to choose between user and machine installation

perhaps you can update the readme and close this issue?
